/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWebhooksRouteImport } from './routes/api/webhooks'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiIncidentsRouteImport } from './routes/api/incidents'
import { Route as ApiWebhooksTestRouteImport } from './routes/api/webhooks/test'
import { Route as ApiStatusRssRouteImport } from './routes/api/status.rss'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksRoute = ApiWebhooksRouteImport.update({
  id: '/api/webhooks',
  path: '/api/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIncidentsRoute = ApiIncidentsRouteImport.update({
  id: '/api/incidents',
  path: '/api/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksTestRoute = ApiWebhooksTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiWebhooksRoute,
} as any)
const ApiStatusRssRoute = ApiStatusRssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => ApiStatusRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/incidents': typeof ApiIncidentsRoute
  '/api/status': typeof ApiStatusRouteWithChildren
  '/api/webhooks': typeof ApiWebhooksRouteWithChildren
  '/api/status/rss': typeof ApiStatusRssRoute
  '/api/webhooks/test': typeof ApiWebhooksTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/incidents': typeof ApiIncidentsRoute
  '/api/status': typeof ApiStatusRouteWithChildren
  '/api/webhooks': typeof ApiWebhooksRouteWithChildren
  '/api/status/rss': typeof ApiStatusRssRoute
  '/api/webhooks/test': typeof ApiWebhooksTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/incidents': typeof ApiIncidentsRoute
  '/api/status': typeof ApiStatusRouteWithChildren
  '/api/webhooks': typeof ApiWebhooksRouteWithChildren
  '/api/status/rss': typeof ApiStatusRssRoute
  '/api/webhooks/test': typeof ApiWebhooksTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api/incidents'
    | '/api/status'
    | '/api/webhooks'
    | '/api/status/rss'
    | '/api/webhooks/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api/incidents'
    | '/api/status'
    | '/api/webhooks'
    | '/api/status/rss'
    | '/api/webhooks/test'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/incidents'
    | '/api/status'
    | '/api/webhooks'
    | '/api/status/rss'
    | '/api/webhooks/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiIncidentsRoute: typeof ApiIncidentsRoute
  ApiStatusRoute: typeof ApiStatusRouteWithChildren
  ApiWebhooksRoute: typeof ApiWebhooksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks': {
      id: '/api/webhooks'
      path: '/api/webhooks'
      fullPath: '/api/webhooks'
      preLoaderRoute: typeof ApiWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/incidents': {
      id: '/api/incidents'
      path: '/api/incidents'
      fullPath: '/api/incidents'
      preLoaderRoute: typeof ApiIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/test': {
      id: '/api/webhooks/test'
      path: '/test'
      fullPath: '/api/webhooks/test'
      preLoaderRoute: typeof ApiWebhooksTestRouteImport
      parentRoute: typeof ApiWebhooksRoute
    }
    '/api/status/rss': {
      id: '/api/status/rss'
      path: '/rss'
      fullPath: '/api/status/rss'
      preLoaderRoute: typeof ApiStatusRssRouteImport
      parentRoute: typeof ApiStatusRoute
    }
  }
}

interface ApiStatusRouteChildren {
  ApiStatusRssRoute: typeof ApiStatusRssRoute
}

const ApiStatusRouteChildren: ApiStatusRouteChildren = {
  ApiStatusRssRoute: ApiStatusRssRoute,
}

const ApiStatusRouteWithChildren = ApiStatusRoute._addFileChildren(
  ApiStatusRouteChildren,
)

interface ApiWebhooksRouteChildren {
  ApiWebhooksTestRoute: typeof ApiWebhooksTestRoute
}

const ApiWebhooksRouteChildren: ApiWebhooksRouteChildren = {
  ApiWebhooksTestRoute: ApiWebhooksTestRoute,
}

const ApiWebhooksRouteWithChildren = ApiWebhooksRoute._addFileChildren(
  ApiWebhooksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiIncidentsRoute: ApiIncidentsRoute,
  ApiStatusRoute: ApiStatusRouteWithChildren,
  ApiWebhooksRoute: ApiWebhooksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
